

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Demo.Core.EntityModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class OnBoadTaskEntities : DbContext
{
    public OnBoadTaskEntities()
        : base("name=OnBoadTaskEntities")
    {

        this.Configuration.LazyLoadingEnabled = false;

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<UserDetail> UserDetails { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserType> UserTypes { get; set; }

    public virtual DbSet<AppointmentTime> AppointmentTimes { get; set; }


    public virtual ObjectResult<GetAvailableAppointment_Result> GetAvailableAppointment(Nullable<System.DateTime> appointmentDate)
    {

        var appointmentDateParameter = appointmentDate.HasValue ?
            new ObjectParameter("AppointmentDate", appointmentDate) :
            new ObjectParameter("AppointmentDate", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAvailableAppointment_Result>("GetAvailableAppointment", appointmentDateParameter);
    }

}

}

